import streamlit as st

st.title("WOMAC Questionnaire")

with st.form(key="form1"):
    st.subheader("Part A: Pain")
    number1 = st.slider("1.在平地上步行: (1)不痛-(5)痛", min_value=1, max_value=5)
    number2 = st.slider("2.上落樓梯: (1)不痛-(5)痛", min_value=1, max_value=5)
    number3 = st.slider("3.晚上躺在床上時，如干擾睡眠的疼痛: (1)不痛-(5)痛", min_value=1, max_value=5)
    number4 = st.slider("4.坐著或躺著的時候: (1)不痛-(5)痛", min_value=1, max_value=5)
    number5 = st.slider("5.直立的時候: (1)不痛-(5)痛", min_value=1, max_value=5)
    st.subheader("Part B: Stiffness")
    number6 = st.slider("6.早上一醒來時你的僵硬感覺有多嚴重: (1)不覺僵硬-(5)極度僵硬", min_value=1, max_value=5)
    number7 = st.slider("7.日間經過坐著，躺著或休息過後，您僵硬的感覺有多嚴重: (1)不覺僵硬-(5)極度僵硬", min_value=1, max_value=5)
    st.subheader("Part C: Functionality")
    number8 = st.slider("8.落樓梯: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number9 = st.slider("9.上樓梯: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number10 = st.slider("10.從坐時站起來: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number11 = st.slider("11.站立 (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number12 = st.slider("12.彎身向地下: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number13 = st.slider("13.在平地上步行: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number14 = st.slider("14.落車，或上落巴士: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number15 = st.slider("15.行街買東西: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number16 = st.slider("16.穿上短褲或長褲: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number17 = st.slider("17.起床: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number18 = st.slider("18.脫下短褲或長褲: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number19 = st.slider("19.挨在床上: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number20 = st.slider("20.踏進或踏出浴缸: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number21 = st.slider("21.坐著: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number22 = st.slider("22.坐上坐厠或離開坐厠: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number23 = st.slider("23.做粗重家務: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    number24 = st.slider("24.做輕巧家務: (1)沒有困難-(5)極度困難", min_value=1, max_value=5)
    submit = st.form_submit_button(label="Submit")


st.text(number1)
st.text(number2)
st.text(number3)
st.text(number4)
st.text(number5)
st.text(number6)
st.text(number7)
st.text(number8)
st.text(number9)
st.text(number10)
st.text(number11)
st.text(number12)
st.text(number13)
st.text(number14)
st.text(number15)
st.text(number16)
st.text(number17)
st.text(number18)
st.text(number19)
st.text(number20)
st.text(number21)
st.text(number22)
st.text(number23)
st.text(number24)
